use_frameworks!

platform :ios, '8.0'

target 'LPMSMediaLibraryiOS_Example' do
  pod 'LPMSMediaLibraryiOS', :path => '../'

  target 'LPMSMediaLibraryiOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
